# importing libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.axes as ax

from sklearn import datasets
import warnings
warnings.filterwarnings("ignore")

# loading data

In [4]:
data = datasets.fetch_california_housing()

In [5]:
data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [6]:
x=data.data

In [7]:
x

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [8]:
y=data.target

In [9]:
features = data.feature_names
features

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [11]:
print (x_train.shape, y_train.shape)
print (x_test.shape, y_test.shape)

(16512, 8) (16512,)
(4128, 8) (4128,)


# RAndom Forest

In [12]:
from sklearn.ensemble import RandomForestRegressor
rf= RandomForestRegressor(100)
rf= rf.fit(x_train, y_train)

predictions = rf.predict(x_test)

In [13]:
predictions.shape

(4128,)

In [14]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, predictions)

0.2570314982238025

# k-Fold Cross Validation

In [15]:
from sklearn.model_selection import KFold

kfold = KFold(n_splits=5, shuffle=False)

for train_index, test_index in kfold.split(x):
    print("Train - \n", train_index, "\nTest - \n", test_index)
    print("=======\n")
# kfold.split(x)

Train - 
 [ 4128  4129  4130 ... 20637 20638 20639] 
Test - 
 [   0    1    2 ... 4125 4126 4127]

Train - 
 [    0     1     2 ... 20637 20638 20639] 
Test - 
 [4128 4129 4130 ... 8253 8254 8255]

Train - 
 [    0     1     2 ... 20637 20638 20639] 
Test - 
 [ 8256  8257  8258 ... 12381 12382 12383]

Train - 
 [    0     1     2 ... 20637 20638 20639] 
Test - 
 [12384 12385 12386 ... 16509 16510 16511]

Train - 
 [    0     1     2 ... 16509 16510 16511] 
Test - 
 [16512 16513 16514 ... 20637 20638 20639]



In [16]:
rf1= RandomForestRegressor()

n_est = [100, 200, 500]

for n_estimator in n_est:       
    error = []
    for train_index, test_index in kfold.split(x):
        
        x_train, x_test = x[train_index], x[test_index]
        y_train, y_test = y[train_index], y[test_index]
    
        rf1 = RandomForestRegressor(n_estimator)

        rf1 = rf1.fit(x_train, y_train)

        prediction = rf1.predict(x_test)
        
        error.append(mean_squared_error(y_test, prediction))
    print("Results for n_estimator: ", n_estimator)
    print(error)
    print("Average Error = ", sum(error)/len(error))

Results for n_estimator:  100
[0.5187638256429327, 0.34392933957753014, 0.3729968619364553, 0.4405075298760146, 0.4713212124733614]
Average Error =  0.42950375390125883
Results for n_estimator:  200
[0.5174177841769834, 0.34455522598063837, 0.37084039669393176, 0.4440363264176282, 0.4624996201037335]
Average Error =  0.42786987067458304
Results for n_estimator:  500
[0.5230069128783007, 0.34376008404413294, 0.37015962170364336, 0.4421788168408132, 0.4645686557484495]
Average Error =  0.4287348182430679
